version: "3.7"

services:

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                USER_ID: $uid
                GROUP_ID: $gid
        image: buwog-php
        environment:
            XDEBUG_CONFIG: "client_host=172.17.0.1"
        volumes:
            - ${HOME}/.composer:/.composer
            - ./:/var/www
            - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - buwog
    runner:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                USER_ID: $uid
                GROUP_ID: $gid
        image: buwog-php
        command: php craft queue/listen
        depends_on:
            - db
        environment:
            XDEBUG_CONFIG: "client_host=172.17.0.1"
        volumes:
            - ${HOME}/.composer:/.composer
            - ./:/var/www
            - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - buwog
    db:
        image: mariadb:10.5
        environment:
            MYSQL_DATABASE: craft
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 13306:3306
        volumes:
            - db:/var/lib/mysql
        networks:
            - buwog
    nginx:
        image: nginx:1.19-alpine
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - buwog
    mail:
        image: maildev/maildev
        networks:
            - buwog
        ports:
            - 8025:80
    node:
        image: node:12
        user: "${uid}:${gid}"
        ports:
            - 3000:3000
        volumes:
            - ./:/var/www
        networks:
            - buwog
        command: bash -c "cd /var/www && npm i && npm run watch"
        working_dir: /var/www

networks:
    buwog:
        driver: bridge
volumes:
    db:
